// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function AddCustomProvider(input: $models.CustomProviderInput): $CancellablePromise<$models.ConnectionVM> {
    return $Call.ByName("main.App.AddCustomProvider", input).then(($result: any) => {
        return $$createType0($result);
    });
}

export function AwaitOAuth(sessionID: string, name: string): $CancellablePromise<$models.ConnectionVM> {
    return $Call.ByName("main.App.AwaitOAuth", sessionID, name).then(($result: any) => {
        return $$createType0($result);
    });
}

export function BeginOAuth(provider: string): $CancellablePromise<$models.OAuthSessionVM> {
    return $Call.ByName("main.App.BeginOAuth", provider).then(($result: any) => {
        return $$createType1($result);
    });
}

export function BeginReauth(id: string): $CancellablePromise<$models.OAuthSessionVM> {
    return $Call.ByName("main.App.BeginReauth", id).then(($result: any) => {
        return $$createType1($result);
    });
}

export function CancelOAuth(sessionID: string): $CancellablePromise<void> {
    return $Call.ByName("main.App.CancelOAuth", sessionID);
}

export function ClaudeConfig(): $CancellablePromise<string> {
    return $Call.ByName("main.App.ClaudeConfig");
}

export function ClearLogs(): $CancellablePromise<void> {
    return $Call.ByName("main.App.ClearLogs");
}

export function CodexConfig(): $CancellablePromise<string> {
    return $Call.ByName("main.App.CodexConfig");
}

export function CreateKey(name: string): $CancellablePromise<$models.CreatedKeyVM> {
    return $Call.ByName("main.App.CreateKey", name).then(($result: any) => {
        return $$createType2($result);
    });
}

export function DeleteConnection(id: string): $CancellablePromise<void> {
    return $Call.ByName("main.App.DeleteConnection", id);
}

export function DeleteKey(id: string): $CancellablePromise<void> {
    return $Call.ByName("main.App.DeleteKey", id);
}

export function GetSettings(): $CancellablePromise<$models.SettingsVM> {
    return $Call.ByName("main.App.GetSettings").then(($result: any) => {
        return $$createType3($result);
    });
}

export function ListConnections(provider: string): $CancellablePromise<$models.ConnectionVM[]> {
    return $Call.ByName("main.App.ListConnections", provider).then(($result: any) => {
        return $$createType4($result);
    });
}

export function ListKeys(): $CancellablePromise<$models.KeyVM[]> {
    return $Call.ByName("main.App.ListKeys").then(($result: any) => {
        return $$createType6($result);
    });
}

export function Logs(filter: string): $CancellablePromise<$models.LogVM[]> {
    return $Call.ByName("main.App.Logs", filter).then(($result: any) => {
        return $$createType8($result);
    });
}

export function Quota(id: string): $CancellablePromise<$models.QuotaVM> {
    return $Call.ByName("main.App.Quota", id).then(($result: any) => {
        return $$createType9($result);
    });
}

export function RefreshConnection(id: string): $CancellablePromise<$models.ConnectionVM> {
    return $Call.ByName("main.App.RefreshConnection", id).then(($result: any) => {
        return $$createType0($result);
    });
}

export function RenameConnection(id: string, name: string): $CancellablePromise<void> {
    return $Call.ByName("main.App.RenameConnection", id, name);
}

export function Reorder(id: string, delta: number): $CancellablePromise<void> {
    return $Call.ByName("main.App.Reorder", id, delta);
}

export function RestartServer(): $CancellablePromise<$models.ServerStatusVM> {
    return $Call.ByName("main.App.RestartServer").then(($result: any) => {
        return $$createType10($result);
    });
}

export function SaveSettings(settings: $models.SettingsVM): $CancellablePromise<$models.SettingsVM> {
    return $Call.ByName("main.App.SaveSettings", settings).then(($result: any) => {
        return $$createType3($result);
    });
}

export function ServerStatus(): $CancellablePromise<$models.ServerStatusVM> {
    return $Call.ByName("main.App.ServerStatus").then(($result: any) => {
        return $$createType10($result);
    });
}

export function SetEnabled(id: string, enabled: boolean): $CancellablePromise<void> {
    return $Call.ByName("main.App.SetEnabled", id, enabled);
}

export function StartServer(): $CancellablePromise<$models.ServerStatusVM> {
    return $Call.ByName("main.App.StartServer").then(($result: any) => {
        return $$createType10($result);
    });
}

export function StopServer(): $CancellablePromise<$models.ServerStatusVM> {
    return $Call.ByName("main.App.StopServer").then(($result: any) => {
        return $$createType10($result);
    });
}

export function SubmitCallback(sessionID: string, name: string, callbackURL: string): $CancellablePromise<$models.ConnectionVM> {
    return $Call.ByName("main.App.SubmitCallback", sessionID, name, callbackURL).then(($result: any) => {
        return $$createType0($result);
    });
}

export function TestConnection(id: string, model: string): $CancellablePromise<$models.ProviderTestVM> {
    return $Call.ByName("main.App.TestConnection", id, model).then(($result: any) => {
        return $$createType11($result);
    });
}

export function UpdateCustomProvider(id: string, input: $models.CustomProviderUpdate): $CancellablePromise<$models.ConnectionVM> {
    return $Call.ByName("main.App.UpdateCustomProvider", id, input).then(($result: any) => {
        return $$createType0($result);
    });
}

export function Version(): $CancellablePromise<string> {
    return $Call.ByName("main.App.Version");
}

// Private type creation functions
const $$createType0 = $models.ConnectionVM.createFrom;
const $$createType1 = $models.OAuthSessionVM.createFrom;
const $$createType2 = $models.CreatedKeyVM.createFrom;
const $$createType3 = $models.SettingsVM.createFrom;
const $$createType4 = $Create.Array($$createType0);
const $$createType5 = $models.KeyVM.createFrom;
const $$createType6 = $Create.Array($$createType5);
const $$createType7 = $models.LogVM.createFrom;
const $$createType8 = $Create.Array($$createType7);
const $$createType9 = $models.QuotaVM.createFrom;
const $$createType10 = $models.ServerStatusVM.createFrom;
const $$createType11 = $models.ProviderTestVM.createFrom;
