// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class ConnectionVM {
    "id": string;
    "provider": string;
    "name": string;
    "priority": number;
    "enabled": boolean;
    "status": string;
    "needsReauth": boolean;
    "routable": boolean;
    "cooldownUntil": string;
    "consecutiveFailures": number;
    "prefix": string;
    "baseUrl": string;
    "compatType": string;
    "apiType": string;
    "canQuota": boolean;
    "canRefresh": boolean;
    "canReauth": boolean;
    "requesting": boolean;

    /** Creates a new ConnectionVM instance. */
    constructor($$source: Partial<ConnectionVM> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("provider" in $$source)) {
            this["provider"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("priority" in $$source)) {
            this["priority"] = 0;
        }
        if (!("enabled" in $$source)) {
            this["enabled"] = false;
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("needsReauth" in $$source)) {
            this["needsReauth"] = false;
        }
        if (!("routable" in $$source)) {
            this["routable"] = false;
        }
        if (!("cooldownUntil" in $$source)) {
            this["cooldownUntil"] = "";
        }
        if (!("consecutiveFailures" in $$source)) {
            this["consecutiveFailures"] = 0;
        }
        if (!("prefix" in $$source)) {
            this["prefix"] = "";
        }
        if (!("baseUrl" in $$source)) {
            this["baseUrl"] = "";
        }
        if (!("compatType" in $$source)) {
            this["compatType"] = "";
        }
        if (!("apiType" in $$source)) {
            this["apiType"] = "";
        }
        if (!("canQuota" in $$source)) {
            this["canQuota"] = false;
        }
        if (!("canRefresh" in $$source)) {
            this["canRefresh"] = false;
        }
        if (!("canReauth" in $$source)) {
            this["canReauth"] = false;
        }
        if (!("requesting" in $$source)) {
            this["requesting"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ConnectionVM instance from a string or object.
     */
    static createFrom($$source: any = {}): ConnectionVM {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ConnectionVM($$parsedSource as Partial<ConnectionVM>);
    }
}

export class CreatedKeyVM {
    "id": string;
    "name": string;
    "prefix": string;
    "createdAt": string;
    "secret": string;

    /** Creates a new CreatedKeyVM instance. */
    constructor($$source: Partial<CreatedKeyVM> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("prefix" in $$source)) {
            this["prefix"] = "";
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = "";
        }
        if (!("secret" in $$source)) {
            this["secret"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CreatedKeyVM instance from a string or object.
     */
    static createFrom($$source: any = {}): CreatedKeyVM {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CreatedKeyVM($$parsedSource as Partial<CreatedKeyVM>);
    }
}

export class CustomProviderInput {
    "name": string;
    "prefix": string;
    "baseUrl": string;
    "apiKey": string;
    "compatType": string;
    "apiType": string;

    /** Creates a new CustomProviderInput instance. */
    constructor($$source: Partial<CustomProviderInput> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("prefix" in $$source)) {
            this["prefix"] = "";
        }
        if (!("baseUrl" in $$source)) {
            this["baseUrl"] = "";
        }
        if (!("apiKey" in $$source)) {
            this["apiKey"] = "";
        }
        if (!("compatType" in $$source)) {
            this["compatType"] = "";
        }
        if (!("apiType" in $$source)) {
            this["apiType"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CustomProviderInput instance from a string or object.
     */
    static createFrom($$source: any = {}): CustomProviderInput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CustomProviderInput($$parsedSource as Partial<CustomProviderInput>);
    }
}

export class CustomProviderUpdate {
    "name": string;
    "prefix": string;
    "baseUrl": string;
    "apiKey": string;
    "apiType": string;

    /** Creates a new CustomProviderUpdate instance. */
    constructor($$source: Partial<CustomProviderUpdate> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("prefix" in $$source)) {
            this["prefix"] = "";
        }
        if (!("baseUrl" in $$source)) {
            this["baseUrl"] = "";
        }
        if (!("apiKey" in $$source)) {
            this["apiKey"] = "";
        }
        if (!("apiType" in $$source)) {
            this["apiType"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CustomProviderUpdate instance from a string or object.
     */
    static createFrom($$source: any = {}): CustomProviderUpdate {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CustomProviderUpdate($$parsedSource as Partial<CustomProviderUpdate>);
    }
}

export class KeyVM {
    "id": string;
    "name": string;
    "prefix": string;
    "createdAt": string;

    /** Creates a new KeyVM instance. */
    constructor($$source: Partial<KeyVM> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("prefix" in $$source)) {
            this["prefix"] = "";
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new KeyVM instance from a string or object.
     */
    static createFrom($$source: any = {}): KeyVM {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new KeyVM($$parsedSource as Partial<KeyVM>);
    }
}

export class LogVM {
    "time": string;
    "source": string;
    "message": string;

    /** Creates a new LogVM instance. */
    constructor($$source: Partial<LogVM> = {}) {
        if (!("time" in $$source)) {
            this["time"] = "";
        }
        if (!("source" in $$source)) {
            this["source"] = "";
        }
        if (!("message" in $$source)) {
            this["message"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LogVM instance from a string or object.
     */
    static createFrom($$source: any = {}): LogVM {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LogVM($$parsedSource as Partial<LogVM>);
    }
}

export class OAuthSessionVM {
    "id": string;
    "provider": string;
    "accountId": string;
    "authUrl": string;
    "loopback": boolean;
    "loopbackError": string;

    /** Creates a new OAuthSessionVM instance. */
    constructor($$source: Partial<OAuthSessionVM> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("provider" in $$source)) {
            this["provider"] = "";
        }
        if (!("accountId" in $$source)) {
            this["accountId"] = "";
        }
        if (!("authUrl" in $$source)) {
            this["authUrl"] = "";
        }
        if (!("loopback" in $$source)) {
            this["loopback"] = false;
        }
        if (!("loopbackError" in $$source)) {
            this["loopbackError"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new OAuthSessionVM instance from a string or object.
     */
    static createFrom($$source: any = {}): OAuthSessionVM {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new OAuthSessionVM($$parsedSource as Partial<OAuthSessionVM>);
    }
}

export class ProviderTestVM {
    "status": number;
    "ok": boolean;
    "output": string;

    /** Creates a new ProviderTestVM instance. */
    constructor($$source: Partial<ProviderTestVM> = {}) {
        if (!("status" in $$source)) {
            this["status"] = 0;
        }
        if (!("ok" in $$source)) {
            this["ok"] = false;
        }
        if (!("output" in $$source)) {
            this["output"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProviderTestVM instance from a string or object.
     */
    static createFrom($$source: any = {}): ProviderTestVM {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ProviderTestVM($$parsedSource as Partial<ProviderTestVM>);
    }
}

export class QuotaVM {
    "connected": boolean;
    "available": boolean;
    "status": number;
    "fetchedAt": string;
    "retryAt": string;
    "message": string;
    "windows": QuotaWindowVM[];

    /** Creates a new QuotaVM instance. */
    constructor($$source: Partial<QuotaVM> = {}) {
        if (!("connected" in $$source)) {
            this["connected"] = false;
        }
        if (!("available" in $$source)) {
            this["available"] = false;
        }
        if (!("status" in $$source)) {
            this["status"] = 0;
        }
        if (!("fetchedAt" in $$source)) {
            this["fetchedAt"] = "";
        }
        if (!("retryAt" in $$source)) {
            this["retryAt"] = "";
        }
        if (!("message" in $$source)) {
            this["message"] = "";
        }
        if (!("windows" in $$source)) {
            this["windows"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new QuotaVM instance from a string or object.
     */
    static createFrom($$source: any = {}): QuotaVM {
        const $$createField6_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("windows" in $$parsedSource) {
            $$parsedSource["windows"] = $$createField6_0($$parsedSource["windows"]);
        }
        return new QuotaVM($$parsedSource as Partial<QuotaVM>);
    }
}

export class QuotaWindowVM {
    "name": string;
    "utilization": number;
    "resetsAt": string;
    "summary": string;

    /** Creates a new QuotaWindowVM instance. */
    constructor($$source: Partial<QuotaWindowVM> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("utilization" in $$source)) {
            this["utilization"] = 0;
        }
        if (!("resetsAt" in $$source)) {
            this["resetsAt"] = "";
        }
        if (!("summary" in $$source)) {
            this["summary"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new QuotaWindowVM instance from a string or object.
     */
    static createFrom($$source: any = {}): QuotaWindowVM {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new QuotaWindowVM($$parsedSource as Partial<QuotaWindowVM>);
    }
}

export class ServerStatusVM {
    "state": string;
    "configuredEndpoint": string;
    "actualEndpoint": string;
    "host": string;
    "port": number;
    "error": string;

    /** Creates a new ServerStatusVM instance. */
    constructor($$source: Partial<ServerStatusVM> = {}) {
        if (!("state" in $$source)) {
            this["state"] = "";
        }
        if (!("configuredEndpoint" in $$source)) {
            this["configuredEndpoint"] = "";
        }
        if (!("actualEndpoint" in $$source)) {
            this["actualEndpoint"] = "";
        }
        if (!("host" in $$source)) {
            this["host"] = "";
        }
        if (!("port" in $$source)) {
            this["port"] = 0;
        }
        if (!("error" in $$source)) {
            this["error"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ServerStatusVM instance from a string or object.
     */
    static createFrom($$source: any = {}): ServerStatusVM {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ServerStatusVM($$parsedSource as Partial<ServerStatusVM>);
    }
}

export class SettingsVM {
    "host": string;
    "port": number;
    "trayEnabled": boolean;
    "logRequests": boolean;
    "logUpstream": boolean;
    "logBodyLimit": number;
    "defaultModel": string;
    "upstreamTimeoutSeconds": number;

    /** Creates a new SettingsVM instance. */
    constructor($$source: Partial<SettingsVM> = {}) {
        if (!("host" in $$source)) {
            this["host"] = "";
        }
        if (!("port" in $$source)) {
            this["port"] = 0;
        }
        if (!("trayEnabled" in $$source)) {
            this["trayEnabled"] = false;
        }
        if (!("logRequests" in $$source)) {
            this["logRequests"] = false;
        }
        if (!("logUpstream" in $$source)) {
            this["logUpstream"] = false;
        }
        if (!("logBodyLimit" in $$source)) {
            this["logBodyLimit"] = 0;
        }
        if (!("defaultModel" in $$source)) {
            this["defaultModel"] = "";
        }
        if (!("upstreamTimeoutSeconds" in $$source)) {
            this["upstreamTimeoutSeconds"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SettingsVM instance from a string or object.
     */
    static createFrom($$source: any = {}): SettingsVM {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SettingsVM($$parsedSource as Partial<SettingsVM>);
    }
}

// Private type creation functions
const $$createType0 = QuotaWindowVM.createFrom;
const $$createType1 = $Create.Array($$createType0);
